### ISSUE TITLE
Allow `lagoon get` to retrieve variables

### ISSUE THREAD

**Issue by klonos** [amazeeio/lagoon-cli#104]
So `lagoon list variables -p [projectname]` gets you a list of the variables specified for a project, along with the variable ID and its scope, but it does not return the variable values.

Can we please have it so that `lagoon list variables` returns the variable value in another column? (optionally perhaps?)

Alternatively/additionally, can we please have support for something like `lagoon get variable`?

**Comment by shreddedbacon** [comment]
> So `lagoon list variables -p [projectname]` gets you a list of the variables specified for a project, along with the variable ID and its scope, but it does not return the variable values.
> 
> Can we please have it so that `lagoon list variables` returns the variable value in another column? (optionally perhaps?)

This does exist, with the `--reveal` flag.

Will look at adding `lagoon get variable`

**Comment by shreddedbacon** [comment]
There isn't currently any lagoon API to query an environment variable directly. So any `lagoon get variable` would need to list all variables and then search through them.

Not an ideal solution.

**Comment by shreddedbacon** [comment]
Not sure if the usecase for this is high enough to warrant adding the feature to Lagoon.

I'm going to close this, if you think this is in error, feel free to raise the issue in the main Lagoon repository requesting the ability to query for a specific variable by name.

**Comment by klonos** [comment]
Yeah, at the point when I filed this issue, I hadn't noticed the `--reveal` flag. Been using that since, so this is a non-issue. Thanks.
