### ISSUE TITLE
Re-work `config feature` command

### ISSUE THREAD

**Issue by shreddedbacon** [amazeeio/lagoon-cli#128]
The current implementation of the `config feature` command is not very user friendly, and it is confusing.

Currently there are only 2 features, but there may be others in the future.
* CLI automatic update check disable
* lagoon project check disable

It should be easier to set features on and off, and should be able to list the current features that are on or off.

**Comment by shreddedbacon** [comment]
This could be worked in with #127

**Comment by smlx** [comment]
I've actually wondered if the config feature can be removed. Is `lagoon config feature ...` really easier than just editing `~/.lagoon.yml`?

Maybe `lagoon config feature` should just print the current state (which features are on/off), with instructions for toggling them? And remove the ability to edit the config?

**Comment by shreddedbacon** [comment]
I don't know what would be easier. That's why it's the mess that it is now.

It is only two feature flags at this stage, so editing the config file directly seems fine to me as long as it's clear to users how to adjust them.

**Comment by shreddedbacon** [comment]
Closing this, will probably not exist in CLI refresh
