### ISSUE TITLE
lagoon config add -- Error: Missing arguments: Lagoon name is not defined

### ISSUE THREAD

**Issue by simesy** [amazeeio/lagoon-cli#129]
**Describe the bug**
When i run `lagoon config add ...` or `lagoon config add foobar ...` i get a nonsense error "Lagoon name is not defined" when "name" is not a defined parameter. 

**To Reproduce**
```
lagoon config add govcms --create-config --graphql https://api-lagoon.govcms.amazee.io/graphql --hostname ssh-lagoon.govcms.amazee.io --port 30831
```
or 
```
lagoon config add --create-config --graphql https://api-lagoon.govcms.amazee.io/graphql --hostname ssh-lagoon.govcms.amazee.io --port 30831
```

**Expected behavior**
It should add config for `govcms` or explain what i'm doing wrong.

**Screenshots**
<img width="1241" alt="Screen Shot 2020-05-12 at 14 40 48" src="https://user-images.githubusercontent.com/188856/81639183-93755b80-945e-11ea-9cfa-d7de94567cc1.png">

**Desktop (please complete the following information):**
 - Mac OSX 10.15.4
 - iTerm 3.3.9
- lagoon 0.9.0 (go version go1.13.10 linux/amd64) built 2020-05-07T23:20:50+0000

**Additional context**

**Comment by shreddedbacon** [comment]
@simesy you need to add `--lagoon foobar` or `-l foobar` it isn't very clear and we are working on improving this.

```
lagoon config add --lagoon foobar \
 --graphql api.foobar.com \
 --hostname ssh.foobar.com \
 --port 23232 
 --kibana kibana.foobar.com
 --ui ui.foobar.com
```

**Comment by simesy** [comment]
Yuss, thanks.

**Comment by shreddedbacon** [comment]
Just going to add this to documentation improvements

**Comment by simesy** [comment]
Oh yep sorry <3
