### ISSUE TITLE
Expose the name of kubernetes namespace in `environment get` command.

### ISSUE THREAD

**Issue by nicksantamaria** [amazeeio/lagoon-cli#132]
**Is your feature request related to a problem? Please describe.**
When writing glue code and automation between lagoon and kubernetes, you have to assume the kube namespace follows the pattern `[project]-[environment]` which works most of the time, but can potentially break down when there are slashes in the branch name.

**Describe the solution you'd like**

I'd ike to get the exact namespace name from the command line like this:

```
NS=$(lagoon get environment --project=foo --environment=bar --output-json | jq .data.namespace)
k -n ${NS} get pods
```

**Describe alternatives you've considered**
The workaround I'm currently using is

```
NS=$(k get ns --selector=lagoon/project=foo -o custom-columns='':metadata.name | grep bar)
```

**Comment by shreddedbacon** [comment]
Solved in #137

```
$ lagoon get environment -p example-project -e master --output-json | jq -r '.data | .[].openshiftprojectname'
example-project-master

$ lagoon list environments -p example-project --output-json | jq -r '.data | .[].openshiftprojectname'
example-project-master
example-project-staging
example-project-develop
```
