### ISSUE TITLE
List environment variables for a project

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon-cli#14]
Would be nice to know if the environment variables have been modified too, and when (and by whom).

**Comment by shreddedbacon** [comment]
It is possible to list the environment variables for a project and environment in the latest code base that came with the resolution to #15 
```
$ lagoon list variables -p ci-github
ID 	PROJECT  	SCOPE	VARIABLENAME 
123	ci-github	build	TEST_VAR    	
$ lagoon list variables -p ci-github -e master
ID 	PROJECT  	ENVIRONMENT	SCOPE	VARIABLENAME 
124	ci-github	master     	build	TEST_VAR
```
But currently the lagoon API doesn't support knowing who modified an environment variable or when. This would need to be a feature request in https://github.com/amazeeio/lagoon

@seanhamlin are you happy to close this one off?

**Comment by dasrecht** [comment]
Works as intended :)
