### ISSUE TITLE
Avoid returning Error: in an emtpy response.

### ISSUE THREAD

**Issue by ivangrynenko** [amazeeio/lagoon-cli#148]
**Is your feature request related to a problem? Please describe.**
When requesting project-level variables with "lagoon list variables -p projectname" and in the situation there are no variables, lagoon CLI returns this:
"Error: no data returned from the lagoon api"
Such response leads to conclusion something is wrong and the response is not being returned due to an error.

**Describe the solution you'd like**
Avoid wording Error and include a better and more descriptive response, such as "No variables defined" or "Empty list of variables received for PROJECTNAME

**Describe alternatives you've considered**
Using GraphQL to review the response and avoid the "Error" message.

**Additional context**
N/A

**Comment by GROwen** [comment]
+1 - we're using lagoon CLI in CI and the error fails the job even though an empty result set would be acceptable.

**Comment by GROwen** [comment]
related amazeeio/lagoon-cli#105

**Comment by shreddedbacon** [comment]
Do you think it should return an exit code 1 (error) or exit code 0 (ok) if there is no data in the api? 
I think @GROwen what you're seeing is the exit code 1 causing your issue. Where an exit code 0 would be acceptable?

Adjusting the message will be easy enough to do, but I think the exit code is also an issue

**Comment by shreddedbacon** [comment]
@ivangrynenko @GROwen the mentioned PR should fix this up, if you have the ability to build and test it locally and let me know. Otherwise it will be in a release hopefully this week.
