### ISSUE TITLE
Sometimes `~/.lagoon.yml` gets overwritten

### ISSUE THREAD

**Issue by shreddedbacon** [amazeeio/lagoon-cli#162]
**Describe the bug**
Sometimes `~/.lagoon.yml` gets overwritten

**To Reproduce**
Unable to reproduce reliably

**Expected behavior**
File should only be written to when adding, updating, or removing contexts

**Comment by villanlu** [comment]
Hi,

This happened again during the weekend, which caused some of our automatic deployments to fail; we will create a workaround checking the file before actually using the lagoon cli but it would be good if you could look into this.

I don't have much info other than the resulting file after it was overwritten:

`current: amazeeio`

Basically it removed the "default" and "lagoons" blocks.

To quickly fix it I removed the file and ran "lagoon login" to regenerate it:

`current: amazeeio
default: amazeeio
lagoons:
  amazeeio:
    graphql: https://api.lagoon.amazeeio.cloud/graphql
    hostname: ssh.lagoon.amazeeio.cloud
    kibana: https://logs.amazeeio.cloud/
    port: 32222
    token: <token>
    ui: https://dashboard.amazeeio.cloud
    version: v1.13.1
`

**Comment by shreddedbacon** [comment]
I'll look into this and see if I can get a fix out as soon as possible.
