### ISSUE TITLE
Support for setting activeSystemsMisc

### ISSUE THREAD

**Issue by smlx** [amazeeio/lagoon-cli#165]
**Is your feature request related to a problem? Please describe.**
We currently support setting these active systems:
* `--activeSystemsDeploy`
* `--activeSystemsPromote`
* `--activeSystemsRemove`
* `--activeSystemsTask`

But we are missing `--activeSystemsMisc`.

**Describe the solution you'd like**
I'd like `--activeSystemsMisc` support added.

**Describe alternatives you've considered**
The only way to set this at the moment is via manual graphql mutation.

**Additional context**
n/a

**Comment by shreddedbacon** [comment]
PR #166 added support for `activeSystemsMisc` but `promote` still needs to be fixed in Lagoon itself.

**Comment by shreddedbacon** [comment]
Closing this as all the supported flags are in the CLI now, the remaining issues in Lagoon need some attention though (https://github.com/amazeeio/lagoon/issues/2321)
