### ISSUE TITLE
Allow capital letters in e-mail addresses.  

### ISSUE THREAD

**Issue by tnelson-doghouse** [amazeeio/lagoon-cli#168]
**Describe the bug**
If you add a user as "Firstname.Lastname@example.com", it will claim that the user has been created.  However, they do not appear in the user list, and cannot be added to groups.  

**To Reproduce**
1. lagoon add user -E Firstname.Lastname@example.com
2. lagoon add user-groups -E Firstname.Lastname@example.com
3. See error

**Expected behavior**
The user should be added to Lagoon correctly.  

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 32

**Comment by shreddedbacon** [comment]
This is a problem with Lagoon API, we can solve it in the CLI by transforming the input to lowercase, but need to address the problem in the API too.
