### ISSUE TITLE
.lagoon.yml config file contents are cleared

### ISSUE THREAD

**Issue by GROwen** [amazeeio/lagoon-cli#180]
**Describe the bug**
The lagoon-cli config file `~/.lagoon.yml` contents are deleted, except for the `current` property. This results in the following error when trying to run Lagoon CLI commands.
```Unable to refresh token, you may need to run `lagoon login` first, error was couldn't connect to :: dial tcp :0: connect: can't assign requested address```

**To Reproduce**
Not sure. When the error started occurring I started using lagoon-cli in a Docker container I had available to me and put off checking what the issue was until after a restart of the host machine.

**Expected behavior**
Lagoon CLI commands return expected results.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur

**Additional context**
Lagoon version: lagoon 0.10.0 (go version go1.13.15 linux/amd64)

**Comment by shreddedbacon** [comment]
Hi @GROwen this has been tracked here #162 
There is a PR to fix it, just working to release it.
