### ISSUE TITLE
Incorrect docs for deploy command

### ISSUE THREAD

**Issue by jordotech** [amazeeio/lagoon-cli#29]
**Describe the bug**
Using osx lagoon 0.3.0 (installed with homebrew)

[Docs](https://amazeeio.github.io/lagoon-cli/commands/lagoon_deploy/) describe `lagoon deploy [project name] [branch name] [flags]`

Actual syntax is 
`lagoon deploy branch -p myproject -b dev`

**To Reproduce**
1. run `lagoon deploy myproject dev` as described in docs, fails

**Desktop (please complete the following information):**
 - OS: OSX
 - Version 0.3.0

**Comment by shreddedbacon** [comment]
Thanks! I completely forgot to push the updated docs when I released v0.3.0.
I've done that now.

I will add this as a step to the release process.
