### ISSUE TITLE
SSH helper

### ISSUE THREAD

**Issue by twardnw** [amazeeio/lagoon-cli#37]
Problem : connecting to a Lagoon environment via SSH requires a difficult to remember series of SSH parameters and hostnames/ports

Solution : Have Lagoon CLI generate and/or execute the necessary SSH connection string

**Comment by seanhamlin** [comment]
IMO, it should just SSH you in, rather than generate the string. Perhaps the string can be output in debug `-vvv` if you really want to get into the weeds.

**Comment by shreddedbacon** [comment]
The PR I have has `--interactive` will will drop you right in

**Comment by twardnw** [comment]
Could it be flipped the other way? Connect by default and have a switch for displaying the string?

**Comment by shreddedbacon** [comment]
Easy done. Updated the PR and done some tests into some environments, works well.
