### ISSUE TITLE
lagoon web command bug

### ISSUE THREAD

**Issue by jordotech** [amazeeio/lagoon-cli#51]
**Describe the bug**
1. The [docs](https://amazeeio.github.io/lagoon-cli/commands/lagoon_web/) do not say how to use this command correctly, it says `lagoon web [flags]` but it actually requires the project name as the first requirement.  By tinkering I figured out it was (for project ipsum) `lagoon web ipsum`.  

- Please add a **Usage:**  section to each command doc page that shows simple examples.  
- Change the Synopsis to `lagoon web [project name] [flags]`

2. When the browser is opened after running the command, the url is malformed and results in a 500 response.  The correct url pattern is `https://ui-lagoon-master.ch.amazee.io/projects/ipsum` but the lagoon command opens is as `https://ui-lagoon-master.ch.amazee.io/projects?name=ipsum`

**Comment by shreddedbacon** [comment]
I think this was fixed in #41 and should be in the latest release 0.7.0. Which version are you running?

**Comment by jordotech** [comment]
Ah yes, I was on 0.4.0, ran `brew upgrade lagoon` to get to 0.7.0 and the command works with `lagoon web --project ipsum`

Sorry about that!
