### ISSUE TITLE
Token error on re-auth

### ISSUE THREAD

**Issue by smlx** [amazeeio/lagoon-cli#63]
**Describe the bug**

If I have to re-auth to the API to get a new token, sometimes I get an error like this.
```
$ lagoon list projects --all-projects
Error: graphql: Forbidden - Invalid Auth Token: Error decoding token: invalid algorithm
```
I know it's re-authing because I get a `pinentry` popup for my SSH agent.

If I run the `lagoon` command again immediately it will work - and continue working.

**To Reproduce**
1. Wait for your token to expire (or invalidate it by editing `~/.lagoon.yml`).
2. Run a lagoon CLI command.
3. See error.
4. Run another command, works fine this time.

**Expected behavior**
Token should be renewed without error.

**Screenshots**
n/a

**Desktop:**
 - OS: Debian testing

**Additional context**
Debug output (not sure if it's helpful).
Failure:
```
$ lagoon list projects --all-projects --debug
Request: {"query":"\nquery {\nallProjects {\n...Project\n}\n}fragment Project on Project {\nid\ngitUrl\nname,\ndevelopmentEnvironmentsLimit,\nenvironments {\nenvironmentType,\nroute\n}\n}","variables":null}
Error: graphql: Forbidden - Invalid Auth Token: Error decoding token: invalid token
```
Success:
```
$ lagoon list projects --all-projects --debug
Request: {"query":"\nquery {\nallProjects {\n...Project\n}\n}fragment Project on Project {\nid\ngitUrl\nname,\ndevelopmentEnvironmentsLimit,\nenvironments {\nenvironmentType,\nroute\n}\n}","variables":null}
Response: ... snipped
```

**Comment by shreddedbacon** [comment]
I've hit this now too
