### ISSUE TITLE
When deleting things, display more information about it, prior to the confirmation

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon-cli#64]
Currently when you delete a project there is a confirmation, but no additional information is presented to enable you to make this choice

```
$ lagoon delete project --project reports
Deleting reports
✔ Yes
Result: success
```

**Describe the solution you'd like**
Perhaps a simple confirmation message like:

```
$ lagoon delete project --project reports
You are attempting to delete project 'reports' ID 10665, with git URL 'git@github.com/blah.git', are you sure?
```

**Additional context**
The idea here is to prevent people from deleting the wrong thing.

**Comment by shreddedbacon** [comment]
Closing, as there is now more information provided to the user when deleting.
