### ISSUE TITLE
Provide `latest` as a binary on releases

### ISSUE THREAD

**Issue by twardnw** [amazeeio/lagoon-cli#65]
**Is your feature request related to a problem? Please describe.**
For situations where the lagoon-cli needs to be downloaded in a script, a way to download latest would be handy.

**Describe the solution you'd like**
Included a `-latest` binary to download (linux is most desired currently)

**Comment by shreddedbacon** [comment]
Can do this with curl and jq

```
# Linux
curl -s https://api.github.com/repos/amazeeio/lagoon-cli/releases/latest | jq -r '.assets[].browser_download_url' | grep linux-amd64$ | wget -i -

# Mac
curl -s https://api.github.com/repos/amazeeio/lagoon-cli/releases/latest | jq -r '.assets[].browser_download_url' | grep darwin-amd64$ | wget -i -
```

**Comment by smlx** [comment]
cross-platform one-liner :smile: 
```
curl https://api.github.com/repos/amazeeio/lagoon-cli/releases/latest \
| jq -r '.assets[].browser_download_url' \
| grep -i "$(uname -s)-amd64$" \
| wget -i-
```

**Comment by shreddedbacon** [comment]
Without jq

```
curl -s https://api.github.com/repos/amazeeio/lagoon-cli/releases/latest \
  | grep "browser_download_url" \
  | grep -i "$(uname -s)-amd64\"$" \
  | cut -d '"' -f 4 \
  | wget -i-
```

**Comment by twardnw** [comment]
That'll do it :) Thanks!

**Comment by vincenzodnp** [comment]
The above doesn't work anymore.Fixed by this

``curl -s -L https://api.github.com/repos/amazeeio/lagoon-cli/releases/latest   | grep "browser_download_url"   | grep -i "$(uname -s)-amd64\"$"   | cut -d '"' -f 4   | wget -i-``
