### ISSUE TITLE
Adding a ssh-key for a user results in access denied

### ISSUE THREAD

**Issue by stmh** [amazeeio/lagoon-cli#70]
**Describe the bug**
When trying to add a ssh-key do an existing user the command returns the following error-message:

``` 
Error: graphql: Unauthorized: You don't have permission to "add" on "ssh_key"
```

**To Reproduce**
1. run `lagoon add user-sshkey -E xx@XXX.com -K path/to/file  -p project-x -N ssh-rsa`
2. See error

**Expected behavior**
The ssh key gets added.

**Comment by shreddedbacon** [comment]
@stmh this could be a genuine permissions error.
If you're trying to add a key to another user, this is not currently possible in lagoon. See the rbac matrix for more information on roles and permissions https://lagoon.readthedocs.io/en/latest/administering_lagoon/rbac/#lagoon-100-rbac-permission-matrix

But currently the `"add" on "ssh_key"` permission is only available to platform administrators, and self. Unfortunately this means you can't add keys for other people.

**Comment by stmh** [comment]
thats unfortunate as it makes setting up projects and people even more time consuming. But so be it

**Comment by shreddedbacon** [comment]
I understand completely, the CLI is bound to the permissions that are available in Lagoon though. 

If being able to add SSH keys for your team is something you want, you can submit an issue directly against Lagoon here https://github.com/amazeeio/lagoon/issues/new/choose to start the discussion.
