### ISSUE TITLE
Misleading error message for laggon add user-group

### ISSUE THREAD

**Issue by stmh** [amazeeio/lagoon-cli#71]
**Describe the bug**
The error message is misleading when omitting the group flag for adding a user to a user-group.

**To Reproduce**
1. run `lagoon add user-group -E some@email.tld -R developer `
2. Error message: `Error: Must define an email address` 

**Expected behavior**
The error message should mention the missing group parameter, e.g. `Error: missing group parameter`

**Comment by shreddedbacon** [comment]
Thanks for this @stmh this is a relatively new feature in the CLI and the error message was overlooked. I'll work to fix this up.
