### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by klonos** [amazeeio/lagoon-cli#77]
It'd be great if there was a check every 24hrs (in reality if more than 24hrs have passed since last check), and some prompt was shown to notify of the existence of a newer version.

Here's what ddev does for example: https://github.com/drud/ddev/blob/master/pkg/ddevapp/ddevapp.go#L752

**Comment by shreddedbacon** [comment]
@klonos will do some checks, and should make it into the next version.
