### ISSUE TITLE
Specify a config file, or cluster to use directly from the command line

### ISSUE THREAD

**Issue by shreddedbacon** [amazeeio/lagoon-cli#94]
**Is your feature request related to a problem? Please describe.**
When working with the CLI in an automation space, being able to define a specific config file or cluster options directly when running commands

**Describe the solution you'd like**
Be able to either specify the path to a custom config file
```
lagoon --config-file /path/to/config.yml list projects
```
or the main config options for api/ssh access, which will ignore any config files
```
lagoon --graphql https://api.example.com/graphql \
  --token "ey...xyz" \
  --port 2020 \
  --hostname ssh.example.com \
  list projects
```

**Comment by smlx** [comment]
it would be awesome to also be able to specify this via an environment variable.
basically the same way `kubectl` has the `KUBECONFIG` environment variable.

**Comment by shreddedbacon** [comment]
Definitely!
