### ISSUE TITLE
New command to deploy PR environments

### ISSUE THREAD

**Issue by seanhamlin** [amazeeio/lagoon-cli#98]
**Is your feature request related to a problem? Please describe.**

At the moment you can deploy branches and not pull requests, it would be great if Lagoon CLI was able to deploy both.

**Describe the solution you'd like**

Something like

```
lagoon deploy pr -p project -b pr-17
```

**Comment by shreddedbacon** [comment]
Not sure it will be that simple :(
The mutation for deploying a PR is
```
deployEnvironmentPullrequest(input: DeployEnvironmentPullrequestInput!)
```
And the input is
```
DeployEnvironmentPullrequestInput {
    project: ProjectInput!
    number: Int!
    title: String!
    baseBranchName: String!
    baseBranchRef: String!
    headBranchName: String!
    headBranchRef: String!
  }
```

Not sure how to populate the `baseBranch*` and `headBranch*` inputs easily.
